import { z } from 'zod';

export const LINK_TYPE = {
  REUSABLE: 'REUSABLE',
  ONE_TIME: 'ONE_TIME',
} as const;

export type LinkType = (typeof LINK_TYPE)[keyof typeof LINK_TYPE];

const baseSchema = z.object({
  title: z.string().trim().min(1).max(255),
  description: z.string().max(1000).optional(),
  linkType: z.enum(['REUSABLE', 'ONE_TIME']).default('REUSABLE'),
  amount: z.number().int().positive().max(10_000_000).optional(),
  minAmount: z.number().int().positive().optional(),
  maxAmount: z.number().int().positive().optional(),
  expiresAt: z.string().datetime().optional(),
  // ONE_TIME customer details (externalOrderId is auto-generated by the server)
  customerName: z.string().trim().min(2).max(100).optional(),
  customerEmail: z.string().email().optional(),
  customerPhone: z
    .string()
    .regex(/^[6-9]\d{9}$/, 'Invalid Indian mobile number')
    .optional(),
});

export const CreatePaymentLinkSchema = baseSchema
  .refine(
    (d) => !d.amount || (!d.minAmount && !d.maxAmount),
    { message: 'Cannot set fixed amount and min/max bounds together' },
  )
  .refine(
    (d) => !d.minAmount || !d.maxAmount || d.minAmount <= d.maxAmount,
    { message: 'minAmount must be less than or equal to maxAmount' },
  )
  .refine(
    (d) => d.linkType !== 'ONE_TIME' || !!d.amount,
    { message: 'One-time payment links must have a fixed amount' },
  );

export type CreatePaymentLinkInput = z.infer<typeof CreatePaymentLinkSchema>;

export const UpdatePaymentLinkSchema = z.object({
  title: z.string().trim().min(1).max(255).optional(),
  description: z.string().max(1000).optional(),
  isActive: z.boolean().optional(),
  expiresAt: z.string().datetime().nullable().optional(),
});

export type UpdatePaymentLinkInput = z.infer<typeof UpdatePaymentLinkSchema>;

export const InitiateLinkSchema = z.object({
  // Optional when the link has customerName pre-set (ONE_TIME links)
  customerName: z.string().trim().min(2).max(100).optional(),
  // Required for variable-amount links
  amount: z.number().int().positive().max(10_000_000).optional(),
});

export type InitiateLinkInput = z.infer<typeof InitiateLinkSchema>;
