/**
 * Auto-generated by scripts/generate-config.js.
 * Do not edit this file directly.
 */
const GeneratedConfig = {
  SEEDHAPE_API_TARGET: "device",
  SEEDHAPE_CLERK_PUBLISHABLE_KEY: "pk_test_REPLACE_ME",
  SEEDHAPE_API_URL_ANDROID_EMULATOR: "http://10.0.2.2:3001",
  SEEDHAPE_API_URL_ANDROID_DEVICE: "http://192.168.0.7:3001",
  SEEDHAPE_API_URL_PROD: "https://api.seedhape.in",
};

export default GeneratedConfig;
