const fs = require('fs');
const path = require('path');

const appRoot = path.resolve(__dirname, '..');
const envPath = path.join(appRoot, '.env');
const outputPath = path.join(appRoot, 'src', 'config.generated.ts');

const defaults = {
  SEEDHAPE_API_TARGET: 'device',
  SEEDHAPE_CLERK_PUBLISHABLE_KEY: 'pk_test_REPLACE_ME',
  SEEDHAPE_API_URL_ANDROID_EMULATOR: 'http://10.0.2.2:3001',
  SEEDHAPE_API_URL_ANDROID_DEVICE: 'http://192.168.0.7:3001',
  SEEDHAPE_API_URL_PROD: 'https://api.seedhape.in',
};

function parseEnv(text) {
  const out = {};
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq <= 0) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

let envVars = {};
if (fs.existsSync(envPath)) {
  envVars = parseEnv(fs.readFileSync(envPath, 'utf8'));
}

const config = {
  SEEDHAPE_API_TARGET: envVars.SEEDHAPE_API_TARGET ?? defaults.SEEDHAPE_API_TARGET,
  SEEDHAPE_CLERK_PUBLISHABLE_KEY:
    envVars.SEEDHAPE_CLERK_PUBLISHABLE_KEY ?? defaults.SEEDHAPE_CLERK_PUBLISHABLE_KEY,
  SEEDHAPE_API_URL_ANDROID_EMULATOR:
    envVars.SEEDHAPE_API_URL_ANDROID_EMULATOR ?? defaults.SEEDHAPE_API_URL_ANDROID_EMULATOR,
  SEEDHAPE_API_URL_ANDROID_DEVICE:
    envVars.SEEDHAPE_API_URL_ANDROID_DEVICE ?? defaults.SEEDHAPE_API_URL_ANDROID_DEVICE,
  SEEDHAPE_API_URL_PROD:
    envVars.SEEDHAPE_API_URL_PROD ?? defaults.SEEDHAPE_API_URL_PROD,
};

const generated = `/**
 * Auto-generated by scripts/generate-config.js.
 * Do not edit this file directly.
 */
const GeneratedConfig = {
  SEEDHAPE_API_TARGET: ${JSON.stringify(config.SEEDHAPE_API_TARGET)},
  SEEDHAPE_CLERK_PUBLISHABLE_KEY: ${JSON.stringify(config.SEEDHAPE_CLERK_PUBLISHABLE_KEY)},
  SEEDHAPE_API_URL_ANDROID_EMULATOR: ${JSON.stringify(config.SEEDHAPE_API_URL_ANDROID_EMULATOR)},
  SEEDHAPE_API_URL_ANDROID_DEVICE: ${JSON.stringify(config.SEEDHAPE_API_URL_ANDROID_DEVICE)},
  SEEDHAPE_API_URL_PROD: ${JSON.stringify(config.SEEDHAPE_API_URL_PROD)},
};

export default GeneratedConfig;
`;

fs.writeFileSync(outputPath, generated);
console.log(`[mobileapp] generated ${path.relative(appRoot, outputPath)}`);
